name: Simple CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run backend tests
      working-directory: ./backend
      run: npm test
      
    - name: Verify code coverage
      working-directory: ./backend
      run: |
        npm run test:coverage
        bash <(curl -s https://codecov.io/bash)

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: test-backend
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test
      
    - name: Build production frontend
      working-directory: ./frontend
      run: npm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push backend
      working-directory: ./backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/open-media-search-backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/open-media-search-backend:latest
        
    - name: Build and push frontend
      working-directory: ./frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/open-media-search-frontend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/open-media-search-frontend:latest